### ISSUE TITLE
Putting a MongoCursor document into an array while iterating crashes HHVM (Segmentation fault)

### ISSUE THREAD

**Issue by nrobillard** [mongofill/mongofill-hhvm#12]
In general, I am getting frequent HHVM crashes using MongoFill. Specifically, I am observing HHVM crashing with a seg fault when I put a MongoCursor document into an array while iterating over the MongoCursor result obj (example below). I'm getting no helpful errors beyond "Core dumped: Segmentation fault" in /var/log/hhvm/error.log, a WSOD in the browser with a "502 Bad Gateway" http status and a cryptic Stacktrace (below).

To give some context - this is code that worked without errors using PHP-FPM.

Here is an example:

    $m = new MongoClient();
    $db = $m->mydb;
  
    $response = array();
          
    $items = $db->mycollection->find();
    foreach ($items as $item) {
      $response[] = $item; // This causes Seg Fault
    }

I can work around this by only pulling out the fields that I want. For example:

    ...
    foreach ($items as $item) {
      $item2 = array();
      $item2['field1'] = $item['field1'];
      $item2['field2'] = $item['field2'];
      $response[] = $item2; // No more Seg Fault
    }

This may have something to do with internal iterator_to_array() conversion that is happening but I'm not at all sure.

Here is my stacktrace log: http://pastebin.com/raw.php?i=gsFTXG8N I don't know what most of it means but maybe I'm missing something obvious.

I'm currently trying to recompile HHVM in debug mode in hopes it will give me more helpful error messages. However for some reason at 100% of the "make" process I get an error while "Linking CXX executable hhvm" (maybe out of memory?). So this is the best I can do for now. Please refer to the Stacktrace for HHVM version info.

**Comment by mcuadros** [comment]
this still happen in the new HHVM versions?
