### ISSUE TITLE
Problems connecting to a replicaset

### ISSUE THREAD

**Issue by nitroxido** [mongofill/mongofill-hhvm#30]
When I try to connect to a replicaset I am obtaining these errors in the log file (dates, times and ips redacted):

[] [hphp] [20869:7f7113bff700:30:000001] [] \nNotice: Use of undefined constant MONGOFILL_USE_APC - assumed 'MONGOFILL_USE_APC'
[] [hphp] [20869:7f7113bff700:30:000002] [] \nNotice: Use of undefined constant MONGOFILL_USE_APC - assumed 'MONGOFILL_USE_APC'
[] [hphp] [20869:7f7113bff700:30:000003] [] \nWarning: failed to connect to <serverip> [111]: Connection refused
[] [hphp] [20869:7f7113bff700:30:000004] [] \nFatal error: Class undefined: MongoConnectionException

My connection string (fake names) is:

mongodb://<server1>:<port1>,<server2>:<port2>,<server3>:<port3>,<server4>:<port4>/<dbname>?replicaSet=<rsname>

If I do the same connection WITHOUT the replicaSet name, it works like a charm. It also works without problems if I use regular PHP5-FPM server.

I am using version "1.3.0-mongofill" for HHVM and "1.6.0" for PHP5-FPM.

**Comment by mcuadros** [comment]
https://github.com/mongofill/mongofill/pull/85
