### ISSUE TITLE
Compile Error - double-conversion

### ISSUE THREAD

**Issue by ProdigyView** [mongofill/mongofill-hhvm#34]
Issue compiling on centos 7 when installed with yum install hhvm hhvm-devel and libbson installed from the source. I get this following:

cmake .
-- Configuring for HHVM API version 20150212
-- bson Include dir: /usr/local/include/libbson-1.0
-- libbson library: /usr/local/lib/libbson-1.0.so
-- Configuring done
-- Generating done
-- Build files have been written to: /root/mongofill-hhvm
make
Scanning dependencies of target mongo
[ 33%] Building CXX object CMakeFiles/mongo.dir/src/bson.cpp.o
In file included from /usr/local/include/hphp/util/assertions.h:28:0,
                 from /usr/local/include/hphp/util/mutex.h:37,
                 from /usr/local/include/hphp/util/lock.h:20,
                 from /usr/local/include/hphp/runtime/base/base-includes.h:23,
                 from /root/mongofill-hhvm/src/bson.cpp:1:
/usr/local/include/hphp/third-party/folly/Format.h:29:49: fatal error: double-conversion/double-conversion.h: No such file or directory
 #include <double-conversion/double-conversion.h>
                                                 ^
compilation terminated.
make[2]: *** [CMakeFiles/mongo.dir/src/bson.cpp.o] Error 1
make[1]: *** [CMakeFiles/mongo.dir/all] Error 2
make: *** [all] Error 2

**Comment by mcuadros** [comment]
can you try with the lastests versions?
