### ISSUE TITLE
Tests and benchmarks don't work

### ISSUE THREAD

**Issue by francescomucio** [mongofill/mongofill-hhvm#35]
I installed mongofill-hhvm and I tried to execute
    
    php ./vendor/bin/athletic -b tests/bootstrap.php  -p tests/Mongofill/Benchmarks/
    
but it seems to me that files are missing starting from `./vendor/bin/athletic`.
Then I tried to run just `bootstrap.php`, now the missing file was `autoload.php`. 

I think there are just some missing files and maybe my mongofill-hhvm is working fine, but I was looking for a quick way to check that.

**Comment by mcuadros** [comment]
you must to use composer.
