### ISSUE TITLE
Authentication is not working with Mongo 3.0.3

### ISSUE THREAD

**Issue by blasterz** [mongofill/mongofill-hhvm#38]
$m = new MongoClient('mongodb://user:pass@localhost/db');
$db = $m->db;
$res = $db->test->findOne();
var_dump($res);

The output is: 
array(2) {
["$err"]=>
string(40) "not authorized for query on db.test"
["code"]=>
int(13)
}

It works from Python with PyMongo!

**Comment by mcuadros** [comment]
can you try with this PR? https://github.com/mongofill/mongofill/pull/65
