### ISSUE TITLE
was built for HHVM 3.8, and cannot be loaded with HHVM 3.7

### ISSUE THREAD

**Issue by joshuataylor** [mongofill/mongofill-hhvm#39]
When doing 'service hhvm restart':

$ sudo service hhvm restart
 * Restarting HHVM FastCGI Daemon hhvm                                                                                              Uncaught exception: /etc/hhvm/ext/mongo.so was built for HHVM 3.8, and cannot be loaded with HHVM 3.7\n
                                                                                                                             [fail]
$ hhvm --version
HipHop VM 3.7.0 (rel)
Compiler: tags/HHVM-3.7.0-0-gc8baf9cd3cb603e030969bfe24634d5e85549915
Repo schema: 1988ce75e6a571ce9c79c60fd7dc3ca8a5a5d403

**Comment by bogomips** [comment]
same problem here, has someone solved or I should just come back to the 3.7?

**Comment by nlared** [comment]
same

**Comment by mcuadros** [comment]
can you check if still is not working with the latest version?
